# Useful links:
# https://circleci.com/docs/2.0/concepts/
# https://circleci.com/docs/2.0/sample-config/
# https://circleci.com/docs/2.0/oss/
version: 2.1

orbs:
  node: circleci/node@3.0.0

jobs:
  build:
    working_directory: ~/jasmine
    # Reuse Docker container specification given by the node Orb
    executor:
      name: node/default
      tag: '14.16.1'
    steps:
      - checkout
      # Install the latest npm - the node Orb takes care of it
      - node/install-npm
      # Install dependencies - the node Orb take care of installation and dependency caching
      # TODO: Does this cache only across jobs (good) or across builds (possibly bad)?
      - node/install-packages:
          app-dir: ~/jasmine
          cache-path: node_modules
          override-ci-command: npm i
      # Save workspace for subsequent jobs (i.e. test)
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    executor:
      name: node/default
      tag: '14.16.1'
    steps:
      # Reuse the workspace from the build job
      - attach_workspace:
          at: .
      - run:
          name: Check working directory
          command: pwd
      - run:
          name: List dirs
          command: find . -type d -print
      - run:
          name: Report node version
          command: node --version
      - run:
          name: Test
          command: npm test

workflows:
  version: 2
  matrix-tests:
    jobs:
      - node/test:
          version: 14.16.1
      - node/test:
          version: 12.22.1
      - node/test:
          version: 10.24.1
