# Useful links:
# https://circleci.com/docs/2.0/concepts/
# https://circleci.com/docs/2.0/sample-config/
# https://circleci.com/docs/2.0/oss/
# React example: https://github.com/facebook/react-native/blob/master/.circleci/config.yml
# Yarn example: https://github.com/yarnpkg/yarn/blob/master/.circleci/config.yml
version: 2.1

orbs:
  node: circleci/node@3.0.0

executors:
  node14:
    docker:
      - image: circleci/node:14
  node12:
    docker:
      - image: circleci/node:12
  node10:
    docker:
      - image: circleci/node:10

jobs:
  test_node:
    parameters:
      executor:
        type: executor
        # TODO do we need or want a default?
        #       default: node14
    executor: << parameters.executor >>
    steps:
      - checkout
      # TODO: might need node/install-npm
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build
          command: npm run build
      - run:
          name: Run tests
          command: npm test

workflows:
  version: 2
  tests:
    jobs:
      - test_node:
          executor: node14
      - test_node:
          executor: node12
      - test_node:
          executor: node10
