# Run tests against supported Node versions, and (except for pull requests)
# against supported browsers.

# TODO:
# * It would be nice to only run `npm install` once per node version and
#   pass the result to downstream jobs.
# * Set a more reasonable job timeout than the 5 hour default.
# * Re-enable long property tests.

version: 2.1

orbs:
  node: circleci/node@3.0.0

executors:
  node14:
    docker:
      - image: circleci/node:14
  node12:
    docker:
      - image: circleci/node:12
  node10:
    docker:
      - image: circleci/node:10

jobs:
  test_node: &test_node
    parameters:
      executor:
        type: executor
    executor: << parameters.executor >>
    steps:
      - checkout
      - run:
          name: Report Node and NPM versions
          command: echo "Using Node $(node --version) and NPM $(npm --version)"
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build
          command: npm run build
      - run:
          name: Run tests
          command: npm test

  test_node_with_long_property_tests:
    <<: *test_node
    environment:
      JASMINE_LONG_PROPERTY_TESTS: y

  test_browser:
    executor: node14
    environment:
      USE_SAUCE: true
      JASMINE_BROWSER: internet explorer
      SAUCE_BROWSER_VERSION: 11
    steps:
      - checkout
      - run:
          name: Report Node and NPM versions
          command: echo "Using Node $(node --version) and NPM $(npm --version)"
      - run:
          name: Install Sauce Connect
          command: |
            cd /tmp
             curl https://saucelabs.com/downloads/sc-4.6.4-linux.tar.gz | tar zxf -
            chmod +x sc-4.6.4-linux/bin/sc
            sudo cp sc-4.6.4-linux/bin/sc /usr/local/bin
            sc --version
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build
          command: npm run build
      - run:
          name: Open Sauce tunnel
          no_output_timeout: 2m
          command: |
            sc -u ${SAUCE_USERNAME} -k ${SAUCE_ACCESS_KEY} -X 4445 | tee /tmp/sc-output &
            # wait for sauce tunnel up to 1 minute
            while ! fgrep "Sauce Connect is up, you may start your tests." /tmp/sc-output > /dev/null; do
                sleep 1
            done
            if ! nc -z localhost 4445; then
               echo "Can't connect to Sauce tunnel"
               killall sc
               exit 1
            fi
      - run:
          name: Run tests
          command: npm run ci
      - run:
          name: Close Sauce tunnel
          when: always
          command: killall sc

workflows:
  version: 2
  tests:
    jobs:
 #     - test_node_with_long_property_tests:
      - test_node:
          executor: node14
          name: test_node_14
      - test_node:
          executor: node12
          name: test_node_12
      - test_node:
          executor: node10
          name: test_node_10
      - test_browser:
          name: internet_explorer_11
          filters:
            branches:
              # Don't run on pull requests.
              ignore: /pull\/.*/
