version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
        override-ci-command: npm install
      - run: npm run test
workflows:
  node-tests:
    jobs:
      - test
